bag_file: "/home/nail/stuff/rgb-ir/rgb-ir-extrinsics/frluas3_2025-12-07-23-00-56.bag"
output_dir: "/home/nail/stuff/rgb-ir/rgb-ir-extrinsics/frames"
sync: true
time_tol: 0.005
start_index: 0
end_index: 100
topics:
  /frluas3/camera_array/cam0/image_raw:
   grayscale: false
   clahe: false
  /frluas3/boson_camera_array/cam_0/image_raw:
    to_8bit: false
    norm: true
    clahe: true
    time_offset: -0.025
  /frluas3/boson_camera_array/cam_1/image_raw:
    to_8bit: false
    norm: true
    clahe: true
    time_offset: -0.025
  /frluas3/camera_array/cam1/image_raw:
   grayscale: false
   clahe: false
  

